# Generated by Django 4.2.5 on 2023-09-13 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0001_initial'),
        ('comments', '0007_alter_comment_content'),
        ('posts', '0003_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='post_comments', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', through='likes.Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
