# Generated by Django 4.2.4 on 2023-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.ManyToManyField(related_name='posts', to='posts.post'),
        ),
    ]
