# Generated by Django 4.2.4 on 2023-08-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_title'),
        ('comments', '0004_remove_comment_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.ManyToManyField(null=True, related_name='posts', to='posts.post'),
        ),
    ]
