# Generated by Django 4.2.4 on 2023-08-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_title'),
        ('comments', '0005_remove_comment_object_id_comment_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.ManyToManyField(related_name='posts', to='posts.post'),
        ),
    ]
