PUT http://localhost:8000/group/14/
Content-Type: application/json
Authorization: Token c746632883ab7c54fc246e184eaf15700e1db228


{
    "id": 2,
    "name": "Group 111 updated",
    "description": "test",
    "users": [
        2, 1
    ],
    "admins": [
        1
    ]
}